# -*- coding: utf-8 -*-
"""BibliotecaPanda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JLe-jqiSdynmSKWStqGkIq7l_glxu7fB
"""

#importando a biblioteca
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/taylor_swift_spotify.csv')

#Visualizando as 5 primeiras linhas
df.head()

#Total de linhas e colunas
df.shape

#Nome de colunas
df.columns

#Tipos de dados em cada colunas
df.dtypes

#Visualizando as últimas linhas
df.tail()

#Informações estatísticas sobre o banco de dados da taytay <3
df.describe()

#Retornando valores apenas de uma coluna
df['album'].unique()

#Retornando valores apenas do evermore
evermore = df.loc[df['album'] == 'evermore']
evermore.head()

#Agrupamento de Dados
df.groupby('album')['name'].nunique()

#média
df['popularity'].mean()

#soma
df['popularity'].sum()

"""# Visualização de Dados"""

df['album'].value_counts(ascending = False)

#Gráfico de barras
df['album'].value_counts(ascending = False).plot.bar()

#Gráfico de barras horizontais
df['album'].value_counts(ascending = True).plot.barh()

#Adicionando título e nome nos eixos
import matplotlib.pyplot as plt
df['album'].value_counts().plot.barh(title = 'albuns da taytay ')
plt.xlabel('Número de Músicas')
plt.ylabel('Albuns')

#alterando a cor
df['album'].value_counts().plot.barh(title = 'albuns da taytay ', color = 'pink')
plt.xlabel('Número de Músicas')
plt.ylabel('Albuns')